#pragma once

#ifndef __ASSEMBLER__
enum layers {
    MAC_BASE,
    MAC_FN,
    WIN_BASE,
    WIN_FN,
    GREEK,
    MATH
};
#endif

#define DYNAMIC_KEYMAP_LAYER_COUNT 6
#undef CAPS_LOCK_LED_INDEX

// RGB Matrix configuration
#ifdef RGB_MATRIX_ENABLE

#define RGB_MATRIX_INDICATORS
#define INDICATORS_CAPSLOCK_LIGHT_ALPHAS
#define INDICATORS_CAPSLOCK_LIGHT_KEY
#define INDICATORS_CAPSLOCK_LIGHT_UNICODE_PAIRS
#define INDICATORS_CAPSLOCK_COLOR RGB_RED
#define INDICATORS_CAPSLOCK_ACTIVE_LAYERS MAC_BASE, WIN_BASE, GREEK, MATH

#define RGB_MATRIX_FUNCTIONFILTER
#define FUNCTIONFILTER_LAYERS MAC_FN, WIN_FN, GREEK, MATH

#define RGB_DISABLE_WHEN_USB_SUSPENDED
#define RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS

#endif

// Space cadet configuration
#define LCPO_KEYS KC_LCTL, KC_LSFT, KC_LBRC
#define RCPC_KEYS KC_RCTL, KC_RSFT, KC_RBRC

// Unicode config
#define UNICODE_SELECTED_MODES UNICODE_MODE_WINCOMPOSE
